export { rng, RNG } from './rng.browser.js';
export { deterministic } from './presets.browser.js';

export { normal, exponential, uniform, poisson, normals, exponentials } from './utils/distributions.js';
export { beta, gamma, chi2, binomial, geometric } from './utils/distributions-extra.js';
export { weibull, lognormal, rayleigh, cauchy } from './utils/distributions-special.js';
export { dirichlet, dirichlets, mixture, mixtures, studentT, studentTs, betaBinomial } from './utils/distributions-advanced.js';
export { shuffle, pick, sample, sampleWithReplacement, permute, range, cycle } from './utils/sequence.js';
export { saveState, restoreState, cloneGenerator } from './utils/state.js';
export { weightedPick, weightedSample, reservoirSample } from './utils/sampling.js';
export { meanTest, varianceTest, kolmogorovSmirnovTest, chiSquareTest, entropy, autocorrelation, runTest, skewness, kurtosis, median, quantile } from './utils/statistics.js';
export { combined, clearCryptoCache } from './utils/entropy.browser.js';
export { brownianMotion, ornsteinUhlenbeck, geometricBrownian } from './utils/stochastic.js';
export { categorical, multinomial, categorical2D } from './utils/categorical.js';
export { perlin2D, valueNoise } from './utils/noise.js';
export { combinations, permutations, kPermutations, randomCombination, randomPermutation } from './utils/combinatorics.js';
export { rotateBits, extractBits, hammingWeight, bitRange, popcountNum, clz, ctz, reverseBits, setBit, clearBit, toggleBit } from './utils/bits.js';
export { SeedSequence, seedMultiple } from './utils/seeding.js';
export { seedFromTime, seedFromEntropy } from './utils/seed.js';
export { repeat, until, times } from './utils/helpers.js';
export { bootstrap, jackknife, crossValidation, permutationTest } from './utils/resampling.js';
export { stratifiedSample, stratifiedSampleProportional, stratify } from './utils/stratified.js';
export { cdf, ppf, sf } from './utils/probability.js';
export { WeightedDistribution, CategoricalDistribution, NormalDistribution } from './utils/precomputed.js';
export { bootstrapCI, meanCI, proportionCI } from './utils/confidence.js';
export { cohensD, hedgesG, correlation, cramersV, etaSquared, glasssDelta } from './utils/effects.js';
export { sum, mean, min, max, unique, chunk, flatten, zip, transpose, partition } from './utils/arrays.js';
export { tTest, welchTTest, mannWhitneyU, oneWayAnova } from './utils/hypothesis.js';
export { zscore, standardize, minMaxScale, logTransform, sqrtTransform, rank, robustScale } from './utils/transforms.js';
export { LinearRegression, MultipleRegression } from './utils/regression.js';
export { diff, lag, shift, sma, ema, acf, pacf } from './utils/timeseries.js';
export { matrixAdd, matrixSub, matrixMul, elementwiseMul, scalarMul, determinant, trace, norm, inverse as matrixInverse } from './utils/matrix.js';
export { trapezoidal, simpsons, adaptiveSimpson, gaussQuadrature, numericalDerivative, numericalSecondDerivative } from './utils/integration.js';
export { LinearInterpolator, CubicSplineInterpolator, lagrangeInterpolation, polynomialFit } from './utils/interpolation.js';
export { bisection, newtonRaphson, secant, falsePosition, fixedPoint } from './utils/rootfinding.js';
export { eulerMethod, rk4, systemEuler, systemRK4, rk45Adaptive } from './utils/odesolvers.js';
export { svd, qr, cholesky, lu } from './utils/decomposition.js';
export { gradientDescent, momentumDescent, adam, simplex, brent } from './utils/optimization.js';
export { tTestPValue, zTestPValue, fTestPValue, chi2PValue, uTestPValue, pearsonPValue } from './utils/pvalues.js';
export { residualDiagnostics, leverageValues, cookDistance, durwinWatson, vif } from './utils/diagnostics.js';
export { LogisticRegression } from './utils/logistic.js';
